### ISSUE TITLE
Read-file-fn semplification

### ISSUE THREAD

**Issue by arichiardi** [ScalaConsultants/replumb#31]
I was thinking of semplifying the [`read-line-fn` ](https://github.com/ScalaConsultants/replumb/blob/master/src/cljs/replumb/target/nodejs.cljs#L26) code a bit.

In particular maybe we can make it synchronous, as in any case the code path is already pretty much synchronous by itself.

Basically my change would be:

```clojure
(defn- read-some
  "Reads the first filename in a sequence of supplied filenames,
  using a supplied read-file-fn, calling back upon first successful
  read, otherwise calling back with nil."
  [[filename & more-filenames] read-file-fn cb]
  (if filename
    (if source (read-file-fn filename)
        (cb {:lang (filename->lang filename)
             :source source})
        (read-some more-filenames read-file-fn cb))
    (cb nil)))
```

...and maybe I will make it tail recursive...thoughts?

cc @mfikes

**Comment by mfikes** [comment]
I had made it async only because the Node file reading code I copied from Joel Martin is async. If that can be avoided, sync is simpler.

**Comment by arichiardi** [comment]
Let's see then if Joel (@kanaka) can help us on this :smile:

**Comment by mfikes** [comment]
Looks like Node has sync filesystem APIs as well as async.

**Comment by arichiardi** [comment]
Lol I was checking exactly that, [readFile](https://github.com/ScalaConsultants/replumb/blob/master/repl-demo/node/cljs/nodejs_repl/core.cljs#L15) ` and `readFileSync`...

**Comment by kanaka** [comment]
If it's fully async then it can support a browser environment too using ajax to load files (although that also implies read-file-fn needs to be async too). That's why I tried to use async since I was trying to support both browser and node.js from the same code-base i.e. even clojurescript.net can load files from the origin, or at least it could at one point. There are a few contexts that provide a few sync version of functions (Web Workers, Node.js), but async is universal for JS while sync is not. But synchronous is certainly a lot easier :-)

**Comment by arichiardi** [comment]
Ok, thanks for the answer, there is enough evidence to leave it like this. I was a bit worried because there is a hint to callback nesting in the replumb.target.nodejs namespace...a callback calling a callback, but I might just be paranoid :smile:
